"""empty message

Revision ID: 493dbc952905
Revises: 57919f41da72
Create Date: 2021-12-21 16:30:06.176217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493dbc952905'
down_revision = '57919f41da72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poke_name', sa.String(length=150), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=150), nullable=True),
    sa.Column('move', sa.String(length=150), nullable=True),
    sa.Column('move_text', sa.String(length=250), nullable=True),
    sa.Column('move_description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
