"""empty message

Revision ID: 57919f41da72
Revises: d337d13b1050
Create Date: 2021-11-28 22:20:29.155584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57919f41da72'
down_revision = 'd337d13b1050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_exp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_exp')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
